package avventur.type;

public enum CommandType {
    END, INVENTORY, NORD, SOUTH, EAST, WEST, OPEN, CLOSE, PUSH, RELOAD, PULL, INSERT, DOWNLOAD, PICK_UP, USE, LOOK_AT, TURN_OFF, ESCAPE, STAB, SHOOT, SAVE, SMOKE, OPEN_WITH_CARD, READ, TURN_ON, GO_UP, LAUNCH, GO, DRAW_BLOOD, LEAVE
}
